stu_ad/config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  post 'students/index'
  resources :students
  resources :course
  post  'course/new'
  get 'course/show'
  post 'course/show'
  post 'students/new'
end

stu_ad/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

stu_ad/app/models/course.rb
class Course < ApplicationRecord
end

stu_ad/app/models/student.rb
class Student < ApplicationRecord
end

stu_ad/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

stu_ad/app/controllers/course_controller.rb
class CourseController < ApplicationController

  def new
    @courses = Course.all.order(:created_at)
  end

  def index
  end

  def show
    @course = Course.find(params[:temp])
  end

  def destroy
    @course = Course.find(params[:id])
    @course.destroy
    redirect_to new_course_path
  end

  def edit
    @course = Course.find(params[:id])
  end

  def update
    @course = Course.find(params[:id])
    if @course.update(name: params[:course][:name], duration: params[:course][:duration], fee: params[:course][:fee], coordinator: params[:course][:coordinator])
      redirect_to action: "new"
    else
      render 'edit'
    end
  end
end

stu_ad/app/controllers/students_controller.rb
class StudentsController < ApplicationController

  def new

  end

  def create
    @student = Student.new(name: params[:student][:name], contact: params[:student][:contact], email: params[:student][:email], father: params[:student][:father], age: params[:student][:age])
    @student.save
    redirect_to action: "new"
  end

  def index
     @students = Student.all.order(:created_at)
  end

  def show
    @student = Student.find(params[:id])
  end

  def edit
    @student = Student.find(params[:id])
  end

  def update
    @student = Student.find(params[:id])
    if @student.update(name: params[:student][:name], contact: params[:student][:contact], email: params[:student][:email], father: params[:student][:father],age: params[:student][:age])
      redirect_to students_path
    else
      render 'edit'
    end
  end

  def destroy
    @student = Student.find(params[:id])
    @student.destroy
    redirect_to students_path
  end
end

stu_ad/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

stu_ad/app/helpers/application_helper.rb
module ApplicationHelper
end

stu_ad/app/helpers/course_helper.rb
module CourseHelper
end

stu_ad/app/helpers/student_helper.rb
module StudentHelper
end

stu_ad/app/helpers/students_helper.rb
module StudentsHelper
end

stu_ad/app/helpers/welcome_helper.rb
module WelcomeHelper
end

stu_ad/app/views/course/edit.html.erb
<!DOCTYPE html>
<html>
  <head>
  </head>
  <body>
    <h1>Edit Course</h1>
    <%= form_for @course, as: :course, url: course_path(@course), method: :patch do |f| %>
      <p>
        <%= f.label :Name %><br>
        <%= f.text_field :name %>
      </p>
      <p>
        <%= f.label :Duration %><br>
        <%= f.text_field :duration %>
      </p>
      <p>
        <%= f.label :Fee %><br>
        <%= f.text_field :fee %>
      </p>
      <p>
        <%= f.label :Coordinator %><br>
        <%= f.text_field :coordinator %>
      </p>
      <p>
        <%= f.submit :Update %>
      </p>
    <% end %>
  </body>
</html>

stu_ad/app/views/course/new.html.erb
<!DOCTYPE html>
<html>
  <head>
  </head>
  <body>
    <h1>List of courses</h1>
    <ul>
      <% @courses.each do |course| %>
        <li><%= link_to course.name, :controller => "course", :action => "show", :temp => course.id %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <%= link_to 'Delete Course', course_path(course), method: :delete, data: { confirm: 'Are you sure?' } %>&nbsp;&nbsp;
            <%= link_to 'Edit Course', edit_course_path(course) %><br><br></li>
      <% end %>
    </ul>
  </body>
</html>

stu_ad/app/views/course/show.html.erb
<!DOCTYPE html>
<html>
  <head>
  </head>
  <body>
    <h1>Course Detail</h1>
      <p>
        <strong>Name: </strong>
        <%= @course.name %>
      </p>
      <p>
        <strong>Duration: </strong>
        <%= @course.duration %>
      </p>
      <p>
        <strong>Fee: </strong>
        <%= @course.fee %>
      </p>
      <p>
        <strong>Coordinator: </strong>
        <%= @course.coordinator %>
      </p>
  </body>
</html>

stu_ad/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StuAd</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

stu_ad/app/views/students/edit.html.erb
<!DOCTYPE html>
<html>
  <head>
  </head>
  <body>
    <h1>Edit Student Detail</h1>
    <%= form_for @student, as: :student, url: student_path(@student), method: :patch do |f| %>
      <p>
        <%= f.label :Name %><br>
        <%= f.text_field :name %>
      </p>
      <p>
        <%= f.label :Contact_No %><br>
        <%= f.text_field :contact %>
      </p>
      <p>
        <%= f.label :Email_Id %><br>
        <%= f.text_field :email %>
      </p>
      <p>
        <%= f.label :Father_Name %><br>
        <%= f.text_field :father %>
      </p>
      <p>
        <%= f.label :Age %><br>
        <%= f.text_field :age %>
      </p>
      <p>
        <%= f.submit :Update %>
      </p>
    <% end %>
  </body>
</html>

stu_ad/app/views/students/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <style>
      table, th, td {
        border: 1px solid black;
        border-collapse: collapse;
      }
      th, td {
        padding: 15px;
      }
    </style>
  </head>
  <body>
    <h1>List of Students</h1>
    <%= link_to 'Logout', :controller => "welcome", :action => "index" %><br><br>
    <%= button_to 'Add Student', new_student_path %><br>
    <%= button_to 'Go To Courses', :controller => "course", :action => "new" %><br>
    <table>
      <tr>
        <th>Name</th>
        <th>Contact No</th>
        <th>Email Id</th>
        <th>Father Name</th>
        <th>Age</th>
      </tr>
      <% @students.each do |student| %>
        <tr>
          <td><%= student.name %></td>
          <td><%= student.contact %></td>
          <td><%= student.email %></td>
          <td><%= student.father %></td>
          <td><%= student.age %></td>
          <td><%= link_to 'Show', student_path(student) %>
          <td><%= link_to 'Edit', edit_student_path(student) %>
          <td><%= link_to 'Delete', student_path(student), method: :delete, data: { confirm: 'Are you sure?' } %>
        </tr>
      <% end %>
    </table>
  </body>
</html>

stu_ad/app/views/students/new.html.erb
<!DOCTYPE html>
<html>
  <head>

  </head>
  <body>
    <h1>Student Registration</h1>
    <%= link_to :Back, students_path %>
    <%= form_for :student, url: students_path do |f| %>
      <p>
        <%= f.label :Name %><br>
        <%= f.text_field :name %>
      </p>

      <p>
        <%= f.label 'Contact No' %><br>
        <%= f.text_field :contact %>
      </p>

      <p>
        <%= f.label 'Email Id' %><br>
        <%= f.text_field :email %>
      </p>

      <p>
        <%= f.label 'Father Name' %><br>
        <%= f.text_field :father %>
      </p>

      <p>
        <%= f.label :Age %><br>
        <%= f.text_field :age %>
      </p>

      <p>
        <%= f.submit :Register %> 
      </p>
    <% end %>
  </body>
</html>

stu_ad/app/views/students/show.html.erb
<!DOCTYPE html>
<html>
  <head>
  </head>
  <body>
    <h1>Student Details</h1>
    <p>
      <strong>Name: </strong>
      <%= @student.name %>
    </p>
    <p>
      <strong>Contact No: </strong>
      <%= @student.contact %>
    </p>
    <p>
      <strong>Email Id: </strong>
      <%= @student.email %>
    </p>
    <p>
      <strong>Father Name: </strong>
      <%= @student.father %>
    </p>
    <p>
      <strong>Age: </strong>
      <%= @student.age %>
    </p>
  </body>
</html>

stu_ad/app/views/welcome/index.html.erb
<!DOCTYPE html>
<html>
  <head>

  </head>
  <body>
    <h1>Welcome Page</h1>

    <%= form_for :student, url: {:controller=>'students', :action=>'index'} do |f| %>

      <p>
        <%= f.label :Email  %><br>
        <%= f.text_field :email %>
      </p>

      <p>
        <%= f.label :Password  %><br>
        <%= f.text_field :password %>
      </p>

      <p>
        <%= f.submit :LogIn %>
      </p>

    <% end %>
  </body>
</html>